
var contents = [
	'<div style="width: 0px;">Dummy row</div>',
	'<div style="width: 680px;">Hello James,<br/>Your problem description is not clear. To better understand your issue please give more details by following below.<br><ol><li>Does issue happen to specific user?</li><li>List detailed reproducible steps.</li><li>After issue reproduced, upload AGILE_HOME/agileDomain/servers/xxx-server/logs/stdout.log file.</li></ol>Thanks<br>Jie<br>Oracle Agile PLM Support</div>',
	'<div style="width: 680px;">SERVER LOG<br>==========<br>java.lang.NullPointerException <br>at com.agile.program.persistence.DiscussionDAO.syncIndex(DiscussionDAO.java:1522) . <br>at com.agile.program.persistence.DiscussionDAO.updateObjectFlags(DiscussionDAO.java:1337) <br>at com.agile.program.manager.DiscussionMgr.updateObjectFlags(DiscussionMgr.java:545) <br>at com.agile.program.service.DiscussionService.updateObjectFlags(DiscussionService.java:608) <br>at com.agile.program.service.DiscussionService.updateActionItemFlags(DiscussionService.java:623) <br><br>FileName<br>------------<br>stdout.log<br><br>FileComment<br>------------<br>log from Managed Server 2</div>',
	'<div style="width: 400px;">SCREENSHOT<br>==========<br>User admin sees "NullPointerException" error when clicks Submit button on Change Order ECO0001.<br><br>FileName<br>------------<br>weberror.jpg<br><br>FileComment<br>------------<br>screenshot from Web Client</div>',
	'<div style="width: 600px;">SCRIPT OUTPUT<br>==========<br>select ctx_report.create_index_script(\'ITEM_CTX_IDX\') from dual;<br><br>begin<br>  ctx_ddl.create_preference(\'ITEM_CTX_IDX_LEX\',\'BASIC_LEXER\');<br>  ctx_ddl.set_attribute(\'ITEM_CTX_IDX_LEX\',\'PRINTJOINS\',\'_-~*\'@#%^&.()+=:";\');<br>end;<br>/<br><br>FileName<br>------------<br>sqlresult.txt</div>',
	'<div style="width: 400px;">WEBEX SUMMARY<br>==========<br>User admin sees "NullPointerException" error when clicks Submit button on Change Order ECO0001.</div>',
	'<div style="width: 600px;">CUSTOMER STATEMENT<br>==================<br>When user runs an advance search for a parts subclass, and the search criteria contains PageThree Text attribute, user sees the below error. The same search is working fine on few machines, but not working for many users (All the times). It is throwing the below error<br>Error visiting expression. <br>&nbsp;&nbsp;&nbsp;&nbsp;com.agile.util.exception.CMDebugException: Error visiting expression. <br>&nbsp;&nbsp;&nbsp;&nbsp;com.agile.util.exception.CMDebugException: Error visiting expression. <br>&nbsp;&nbsp;&nbsp;&nbsp;java.lang.StackOverflowError </div>',
	'<div style="width: 650px;">On :  9.3.4.0 version, Searches <br><br>When attempting to run Advanced Search based on Parts.PageThree.Text attribute, the following error occurs randomly. <br><br>ERROR<br>-----------------------<br>Error visiting expression. <br>com.agile.util.exception.CMDebugException: Error visiting expression. <br>com.agile.util.exception.CMDebugException: Error visiting expression. <br>java.lang.StackOverflowError<br><br><br>STEPS<br>-----------------------<br>The issue can be reproduced at will with the following steps:<br>1. Log on Agile Web Client with any user<br>2. Run Advanced Search with criteria: Items.15-Top Level Assembly (subclass) .PageThree.CEA_MODEL contains "2015-IV-hadoop-230V-noBBU-EU"<br>3. Click Run, user sees above error on Web Client page<br><br><br>BUSINESS IMPACT<br>-----------------------<br>The issue has the following business impact:<br>Due to this issue, business users can not perform the advance search using the particular attribute, which is key for business. They can not see the search results and work on the data.</div>',
	'<div style="width: 600px;">Verified the issue in customer\'s statement:<br><br>CUSTOMER STATEMENT<br>-----------------------<br>When we did an advance search for a parts subclass, and the search criteria contains Page 3. Text attribute, we are getting the below error. The same search is working fine on few machines, but not working for many users (All the times). It is throwing the below error -<br><br>Error visiting expression. <br>com.agile.util.exception.CMDebugException: Error visiting expression. <br>com.agile.util.exception.CMDebugException: Error visiting expression. <br>java.lang.StackOverflowError </div>',
	'<div style="width: 500px;">Hello James,<br>To analyze this issue, below information/data are required.<br><br>1. Upload server logs:<br>&nbsp;&nbsp;AGILE_HOME/agileDomain/server/xxx-server/logs/stdout.log<br>&nbsp;&nbsp;AGILE_HOME/agileDomain/server/xxx-server/logs/stderr.log<br>2. Upload configuration files:<br>&nbsp;&nbsp;AGILE_HOME/agileDomain/config/config.xml<br>&nbsp;&nbsp;AGILE_HOME/agileDomain/config/agile.properties<br>   <br>Thanks<br>Jie</div>',
	'<div style="width: 400px;">See Data Collection example</div>',
	'<div style="width: 600px;">SEARCH<br>=======<br>Note: This is INTERNAL ONLY research.  No action should be taken by the customer on this information. This is research only, and may NOT be applicable to your specific situation.<br><br>Searched on: agile upload window popup special character<br><br>Find: <br>&nbsp;&nbsp;1. Specific User or Users Cannot Add Attachments in Web Client Because File Uploader Window is Blank or Does Not Appear (Doc ID 1968729.1)<br>&nbsp;&nbsp;2. Bug 20190756 - FILE UPLOAD SELECTOR DOES NOT OPEN FOR ONE USER ADD ATTACHMENT IMPOSSIBLE <br><br>Summary:<br>&nbsp;&nbsp;When user ever uploaded file attachment to object, if filename or object name contains special character, bug 20190756 will be triggered and no window popup if click Add button again. So this user cannot upload file attachments.<br>The workaround is to purge bad Upload History data from history_file_upload table.</div>',
	'<div style="width: 600px;">ANALYSIS<br>========<br>Note: This is INTERNAL ONLY research.  No action should be taken by the customer on this information. This is research only, and may NOT be applicable to your specific situation.<br><br>From the SQL result of : select h.object_number, h.file_name, u.loginid from HISTORY_FILE_UPLOAD h, agileuser u where u.id=h.user_id and u.loginid=\'admin\'; <br><br>Find user admin uploaded file attachments to an object F03-1/4\"  which contains a double quotation mark. This special character makes Javascript fail to parse String. So no Upload Window will pop up. This causes this issue.</div>',
	'<div style="width: 500px;">[For known issue]<br>This issue is caused by a know BUG 20190756 that Agile Javascript fails to parse special characters of Upload History data.<br><br>or<br><br>[For new issue]<br> This issue is caused by a special character in Upload History data of admin user.</div>',
	'<div style="width: 600px;">[For known issue] <br>In user\'s environment, user admin ever uploaded file attachment to object object F03-1/4\" which contains a double quotation marks. This will make Agile fails to popup next Window because of below known BUG <br>BUG 20190756 FILE UPLOAD SELECTOR DOES NOT OPEN FOR ONE USER - ADD ATTACHMENT IMPOSSIBLE<br><br>or<br><br>[For new issue]<br>In user\'s environment, user admin ever uploaded file attachment to object object F03-1/4\" which contains a double quotation marks. Agile Javascript fails to successfully parse String due to this special character. So no Upload Window will pop up and user is not able to upload file attachment.</div>',
	'<div style="width: 650px;">TEST CASE<br>=========<br>Note: This is INTERNAL ONLY research.  No action should be taken by the customer on this information. This is research only, and may NOT be applicable to your specific situation.<br><br>Performed following test case on generic system in lab<br><br>1. Logon Agile Web Client as admin user and create a new Part named F03-1/4"<br>2. Upload any file attachment to this Part<br>3. Restart Agile Application Server<br>4. Click Upload button on this Part, find no Upload Window pop up<br>5. Execute SQL:<br>&nbsp;&nbsp;delete  history_file_upload where user_id in (select id from agileuser where loginid=\'admin\');<br>&nbsp;&nbsp;commit;<br>6. Click Upload button again and confirm user is able to upload file attachment again.</div>',
	'<div style="width: 600px;">The solution is to delete Upload History data from history_file_upload for this problem user admin by SQL.<br>&nbsp;&nbsp;delete  history_file_upload where user_id in (select id from agileuser where loginid=\'admin\');<br>&nbsp;&nbsp;commit;<br></div>',
	'<div style="width: 650px;">Remove special character rows from history_file_upload table can have Agile Javascript reads Upload History data successfully and pop up Upload Window to user for file uploading. This resolves customer\'s issue. This solution is justified by below known document.<br>Specific User or Users Cannot Add Attachments in Web Client Because File Uploader Window is Blank or Does Not Appear (Doc ID 1968729.1)<br><br>or<br><br>Remove special character rows from history_file_upload table can have Agile Javascript reads Upload History data successfully and pop up Upload Window to user for file uploading. This resolves customer\'s issue. This solution is justified by previous TEST CASE </div>.',
	'<div style="width: 600px;">Hello James,<br>To resolve this issue, please follow below steps to fix.<br><br>1. Run SQLPLUS to connect to Agile database as agile user<br>2. Run SQL <br>delete  history_file_upload where user_id in (select id from agileuser where loginid=\'admin\');<br>commit;<br>3. User admin upload file attachment again.<br><br>Please note Agile Application Server is not required to restart after SQL is executed.<br><br>Thanks<br>Jie</div>',
	'<div style="width: 400px;">See Data Collection example</div>',
	'<div style="width: 400px;">See Research example</div>',
	'<div style="width: 400px;">See Action Plan example</div>',
	'<div style="width: 400px;">Use KM Template</div>',
	'<div style="width: 400px;">Dummy row</div>'
	
];

$(document).ready(function(){
	$('area').popover({
		measure: 'img.image-map',
		mouseOffset: 20,
		container: 'body',
		followMouse: true,
		html: true,
		trigger: 'hover',
		content: function(){
			return getContent(this.id);
		}
	});
	
});


function getContent(id) {
	return contents[id];
}
